---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: kustomization

resources:
- ingress.yml
- configmap.yml
- configmap-ssl.yml
- nifi.yml
- hpa.yml
- secrets.yml
- service.yml
- sa.yml
- rbac.yml
- pvc-certs.yml

images:
- name: nifi
  newName: docker.io/apache/nifi
  newTag: "2.7.2"
- name: wait
  newName: docker.io/busybox
  newTag: "1.37"
